version: '3.7'
networks:
  network-api: 
    name: network-api
services:
  db:
    container_name: mysql_container
    image: 'mysql:5.7'
    ports:
      - 3308:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./docker-config/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - ./docker-config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=segredo
    # command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - network-api
  api:
    container_name: node_container
    image: 'node:15.0.0'
    ports: 
    - 3000:8080
    volumes:
      - ./application/app.js:/application/app.js
    networks:
      - network-api
    command: ./application/app.js
