version: '3.7'
networks:
  network-api: 
    name: network-api
services:
  db:
    container_name: mysql_container
    image: 'mysql:5.7'
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./docker-config/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - ./docker-config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=segredo
    # command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - network-api
  api:
    container_name: node_container
    working_dir: /application
    image: 'node:15.0.0'  
    ports: 
    - 9001:9001
    volumes:
      - ./backend:/application
      - ./docker-config/node/start_application.sh:/application/start_application.sh
    networks:
      - network-api
    command: /application/start_application.sh

  nginx:
    container_name: nginx_container
    image: nginx:latest
    ports:
      - 3001:80
    volumes:
    - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./frontend/:/var/www/html
    networks:
      - network-api